### ISSUE TITLE
Extract post installation tasks to their own playbook

### ISSUE THREAD

**Issue by e-minguez** [redhat-cip/dci-openshift-agent#1]
It would be nice to extract things such as the cluster authentication configuration & podman configuration to a different 'post-install' playbook rather than the ose-tests one. Currently the authentication is only used by the ose-tests but I think it can be used for some other stuff as well and having a more general 'post-install' playbook is generally a good idea IMHO.
My 2 cents.

**Comment by thekad** [comment]
Solved by 5b353c4f67b5b2bac7f9b9c735c96236426dc759
