### ISSUE TITLE
Use dedicated cluster-roles instead the generic ones

### ISSUE THREAD

**Issue by e-minguez** [redhat-cip/dci-openshift-agent#3]
https://github.com/redhat-cip/dci-openshift-agent/blob/5b353c4f67b5b2bac7f9b9c735c96236426dc759/plays/oc-setup.yml#L78

Just in case, we have already dedicated clusterroles for every test suite here https://github.com/e-minguez/ose-tests/tree/master/rbac
So instead creating the self-provisioner-namespaces clusterrole and give the `nonadmin` user the self-provisioner-namespaces, cluster-reader and admin roles, you can just reconcile the cluster role that you want https://github.com/e-minguez/ose-tests#for-each-test-suite. For instance, openshift-conformance-minimal:
```
oc auth reconcile -f https://raw.githubusercontent.com/e-minguez/ose-tests/master/rbac/osetests-openshift-conformance-minimal.yaml
```

**Comment by thekad** [comment]
Fixed by 9342a7b1b00e4d72ec475491dddeac4c6f1dc82e
