### ISSUE TITLE
Add ansible.cfg to the list of package config file

### ISSUE THREAD

**Issue by colonwq** [redhat-cip/dci-openshift-agent#5]
Can we have the ansible.cfg file added to the list of package config files with a %config(noreplace)?

https://github.com/redhat-cip/dci-openshift-agent/blob/aab02f73aa1ba429a7741057b8f874abc719bf91/dci-openshift-agent.spec#L110

**Comment by thekad** [comment]
I'm sorry, I actually did this back in April 2021 but never updated/closed this issue, my apologies.
